project:
  type: website
  output-dir: docs

website:
  title: "Climate Change and Forest Ecosystems Lab"
  navbar:
    background: "#1b4d3e" #navbar dark green!
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: team.qmd
        text: People
      - href: publications.qmd
        text: Publications
      - href: join.qmd
        text: Join Us
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



